### ISSUE TITLE
Can't mass-assign protected attributes: reputation_name, target_id, target_type, aggregated_by

### ISSUE THREAD

**Issue by dcalixto** [twitter/activerecord-reputation-system#85]
0
down vote
favorite

I followed the http://railscasts.com/episodes/364-active-record-reputation-system

on my User model i Have:

has_many :evaluations, class_name: "RSEvaluation", as: :source

has_reputation :votes, source: {reputation: :votes, of: :articles}, aggregated_by: :sum

def voted_for?(article)
  evaluations.where(target_type: article.class, target_id: article.id).present?
end

Article model i have:

has_reputation :votes, source: :user, aggregated_by: :sum

And Article controller:

def vote
  value = params[:type] == "up" ? 1 : -1
  @article = article.find(params[:id])
  @article.add_or_update_evaluation(:votes, value, current_user)
  redirect_to :back
end

But when i go voting shows:

```
Can't mass-assign protected attributes: reputation_name, value, source_id, source_type, target_id, target_type
```

Anyone is having the same issue?

**Comment by BennyOnGit** [comment]
I'm getting similar errors when simply creating a new project record:
 Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "project"=>{"title"=>"Project MM", "background"=>"test", "address"=>"houston, texas", "is_private"=>"false", "projectimage"=>#<ActionDispatch::Http::UploadedFile:0x007fb7d3e7f990 @tempfile=#<Tempfile:/var/folders/km/sygfmrkd2bbdk0wns03cjfj80000gn/T/RackMultipart20160508-3003-1rgzm04.jpg>, @original_filename="office.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"project[projectimage]\"; filename=\"office.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Create this Project"}
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "project"=>{"title"=>"Project MM", "background"=>"test", "address"=>"houston, texas", "is_private"=>"false", "projectimage"=>#<ActionDispatch::Http::UploadedFile:0x007fb7d3e7f990 @tempfile=#<Tempfile:/var/folders/km/sygfmrkd2bbdk0wns03cjfj80000gn/T/RackMultipart20160508-3003-1rgzm04.jpg>, @original_filename="office.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"project[projectimage]\"; filename=\"office.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Create this Project"}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
WARNING: Can't mass-assign protected attributes for Project: title, background, address, is_private, projectimage
	app/controllers/projects_controller.rb:13:in `create'
WARNING: Can't mass-assign protected attributes for Project: title, background, address, is_private, projectimage
	app/controllers/projects_controller.rb:13:in `create'

I know a fix was pushed a while back for an issue w/ mass-assignment of attributes, but I'm having issues also.
